// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://futiqfjgfvflhsancowy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ1dGlxZmpnZnZmbGhzYW5jb3d5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxODM1NTIsImV4cCI6MjA2NTc1OTU1Mn0.-S-DUFwODXmL0o7BWRiOywcKX8AQoqnLHvEnOT3ywOY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);